chatcode_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChatcodeBlogBundle:Default:index }
HelloTheWorld:
    pattern:  /hello-world
    defaults: { _controller: ChatcodeBlogBundle:Blog:index }
