chatcode_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChatcodeBlogBundle:Default:index }
HelloTheWorld:
    pattern:  /hello-world/{name}
    defaults: { _controller: ChatcodeBlogBundle:Blog:index }
ByebyeWorld:
    pattern:  /byebye-world/{name}
    defaults: { _controller: ChatcodeBlogBundle:Blog:index }
