chatcodeblog_home:
    pattern:  /
    defaults: { _controller: ChatcodeBlogBundle:Blog:index }
chatcodeblog_news:
    pattern:  /actus
    defaults: { _controller: ChatcodeBlogBundle:Blog:index }
chatcodeblog_website:
    pattern:  /site-du-jour
    defaults: { _controller: ChatcodeBlogBundle:Blog:tips }
chatcodeblog_tutorials:
    pattern:  /tutoriels
    defaults: { _controller: ChatcodeBlogBundle:Blog:tips }
chatcodeblog_resources:
    pattern:  /ressources
    defaults: { _controller: ChatcodeBlogBundle:Blog:tips }
chatcodeblog_contact:
    pattern:  /contact
    defaults: { _controller: ChatcodeBlogBundle:Blog:tips }
chatcodeblog_tips:
    pattern:  /astuces
    defaults: { _controller: ChatcodeBlogBundle:Blog:tips }
chatcodeblog_addtips:
    pattern:  /ajouter
    defaults: { _controller: ChatcodeBlogBundle:Blog:addtips }
chatcodeblog_tip:
    pattern:  /astuces/{slug}
    defaults: { _controller: ChatcodeBlogBundle:Blog:tip }
chatcodeblog_sites:
    pattern:  /sites-du-jour
    defaults: { _controller: ChatcodeBlogBundle:Blog:sites }
