chatcode_blog:
    resource: "@ChatcodeBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
    
chatcode_admin:
    resource: "@ChatcodeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    
login:
  pattern: /login
  defaults: { _controller: ChatcodeUserBundle:Security:login }
  
index:
  pattern: /
  defaults: { _controller: ChatcodeUserBundle:Security:login }
  
login_check:
   pattern: /login_check
   
logout:
  pattern: /logout

