chatcode\BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: chatcode\BlogBundle\Entity\CommentRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        author:
            type: string
            length: 255
        message:
            type: text
        date:
            type: datetime
        status:
            type: integer
    lifecycleCallbacks: {  }
