<?php

namespace chatcode\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * websiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class websiteRepository extends EntityRepository
{
}
